<?php
 /**
 * GoMage ProCart Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2016 GoMage (https://www.gomage.com)
 * @author       GoMage
 * @license      https://www.gomage.com/license-agreement/  Single domain license
 * @terms of use https://www.gomage.com/terms-of-use
 * @version      Release: 2.2.0
 * @since        Class available since Release 1.0
 */
 ?>
<?php if(Mage::helper('gomage_procart')->isProCartEnable()): ?>
<script type="text/javascript">
//<![CDATA[	
    var gomage_procart_product_list = <?php echo $this->getProcartProductList(); ?>;
    var gomage_procart_bundle_selection_hash = <?php echo $this->getProcartBundleSelectionHash(); ?>;
//]]>
</script>
<?php endif; ?>